### ISSUE TITLE
iOS8 not be supported!

### ISSUE THREAD

**Issue by Jinkeycode** [sasojadrovski/SJFluidSegmentedControl#4]
Your code is wonderful. Would you mind to support iOS8 ? Because many application must still support iOS8

**Comment by unittesting0** [comment]
I'm looking too!

**Comment by Jinkeycode** [comment]
@unittesting0 I found that SJFluidSegmentedControl can work perfect in iOS8 by dragging swift file into your project instead of using cocopods.

**Comment by Jinkeycode** [comment]
@unittesting0 I found that SJFluidSegmentedControl can work perfectly in iOS8 by dragging swift file into your project instead of using cocopods.

**Comment by sasojadrovski** [comment]
Hey @Jinkeycode @unittesting0,

Sorry for the late reply guys...

Yes, the library should support iOS 8 without any problems. I will update the pod as well, so you will be able to install it via CocoaPods. I will push the update in the following 2 days.

If you are using this library in your applications, feel free to send me their names and links from the App Store. I would be more than happy to include apps that are using this library in the README.

Once again, I am sorry that I have kept you waiting.

Cheers,
Sasho

**Comment by Jinkeycode** [comment]
@sasojadrovski It doesn't matter, and so glad to receive your reply.My app's app store link is 
[https://itunes.apple.com/us/app/you-duuread-zhi-gei-xiang/id1175225244](url) named 'Uread'.

It's my honor to be included in your library in the README. My app is using your library as personal profile page as below.
![uread personal profile page](https://cloud.githubusercontent.com/assets/12148377/21546445/c55b05f0-ce19-11e6-9d28-1fc2febe20fd.jpeg)

But this page is in my debug version, and will be publish to app store in the few days after apple's staff review my application. I wish you can add it to your README using the picture above before that.Thank you very much.

**Comment by sasojadrovski** [comment]
Hey @Jinkeycode @unittesting0,

As promised, I have updated my library to support iOS 8.0+. 🎉  Again, sorry that I have kept you waiting.

@Jinkeycode, I have also added your app to the "Apps using this library" section in the README. Please ping me once your app is approved by Apple. I would love to check it out!

Cheers,
Sasho
